CREATE TABLE [dbo].[TB_BUGQA]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(), 
    [EmbeddingId] UNIQUEIDENTIFIER NULL DEFAULT NULL, 
    [Bugano] NVARCHAR(50) NOT NULL, 
    [TextHtml] NVARCHAR(MAX) NOT NULL,
    [CreatedAt] DATETIME NULL DEFAULT GETDATE(), 
    [UpdatedAt] DATETIME NULL DEFAULT GETDATE()
)
