CREATE TABLE [dbo].[TB_Embeddings] (
    [Id]     UNIQUEIDENTIFIER  NOT NULL DEFAULT NEWSEQUENTIALID(),
    [Vector] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_TB_Embeddings] PRIMARY KEY CLUSTERED ([Id] ASC)
);

