CREATE TABLE [dbo].[TB_Folders]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(), 
    [Name] NVARCHAR(100) NOT NULL, 
    [ParentId] UNIQUEIDENTIFIER NULL DEFAULT NULL, 
    [CreatedAt] DATETIME NULL DEFAULT GETDATE() , 
    [UpdatedAt] DATETIME NULL DEFAULT GETDATE() ,
)
