CREATE TABLE [dbo].[TB_Texts]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(), 
    [Name] NVARCHAR(200) NOT NULL, 
    [FolderId] UNIQUEIDENTIFIER NULL DEFAULT NULL, 
    [EmbeddingId] UNIQUEIDENTIFIER NULL DEFAULT NULL, 
    [TextContent] NVARCHAR(MAX) NOT NULL, 
    [TextHtml] NVARCHAR(MAX) NOT NULL, 
    [CreatedAt] DATETIME NULL DEFAULT GETDATE(), 
    [UpdatedAt] DATETIME NULL DEFAULT GETDATE()
)
