// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using OpenAIAPI.Models;

namespace OpenAIAPI.Models.Configurations
{
    public partial class TB_ChatConfiguration : IEntityTypeConfiguration<TB_Chat>
    {
        public void Configure(EntityTypeBuilder<TB_Chat> entity)
        {
            entity.HasKey(e => e.ChatroomID)
                .HasName("PK__TB_Chat__B83BDF282279876C");

            entity.Property(e => e.ChatroomID).HasDefaultValueSql("(newsequentialid())");

            entity.Property(e => e.ChatName)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.Content).IsRequired();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TB_Chat> entity);
    }
}
