// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using OpenAIAPI.Models;

namespace OpenAIAPI.Models.Configurations
{
    public partial class TB_UserChatroomConfiguration : IEntityTypeConfiguration<TB_UserChatroom>
    {
        public void Configure(EntityTypeBuilder<TB_UserChatroom> entity)
        {
            entity.HasKey(e => new { e.AccountEmail, e.ChatroomID })
                .HasName("PK__TB_UserC__67F4B0C042660CC5");

            entity.Property(e => e.AccountEmail).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TB_UserChatroom> entity);
    }
}
