// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using OpenAIAPI.Models;

namespace OpenAIAPI.Models.Configurations
{
    public partial class TB_UserConfiguration : IEntityTypeConfiguration<TB_User>
    {
        public void Configure(EntityTypeBuilder<TB_User> entity)
        {
            entity.HasKey(e => e.AccountEmail)
                .HasName("PK_TB_User1");

            entity.Property(e => e.AccountEmail).HasMaxLength(100);

            entity.Property(e => e.AccountPassword)
                .IsRequired()
                .HasMaxLength(1000);

            entity.Property(e => e.HeadshotUrl)
                .IsRequired()
                .HasMaxLength(1000);

            entity.Property(e => e.LoginType)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TB_User> entity);
    }
}
