// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenAIAPI.Models
{
    public partial class TB_Chat
    {
        public Guid ChatroomID { get; set; }
        public string ChatName { get; set; }
        public string Content { get; set; }
    }
}