// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenAIAPI.Models
{
    public partial class TB_User
    {
        public string AccountEmail { get; set; }
        public string AccountPassword { get; set; }
        public string UserName { get; set; }
        public string LoginType { get; set; }
        public string HeadshotUrl { get; set; }
    }
}