// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenAIAPI.Models
{
    public partial class TB_UserChatroom
    {
        public string AccountEmail { get; set; }
        public Guid ChatroomID { get; set; }
    }
}