// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
#nullable disable

namespace OpenAIAPI.Models
{
    public partial class OpenAIContext : DbContext
    {
        public OpenAIContext()
        {
        }

        public OpenAIContext(DbContextOptions<OpenAIContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TB_Chat> TB_Chat { get; set; }
        public virtual DbSet<TB_Embeddings> TB_Embeddings { get; set; }
        public virtual DbSet<TB_Folders> TB_Folders { get; set; }
        public virtual DbSet<TB_Texts> TB_Texts { get; set; }
        public virtual DbSet<TB_User> TB_User { get; set; }
        public virtual DbSet<TB_UserChatroom> TB_UserChatroom { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.TB_ChatConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TB_EmbeddingsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TB_FoldersConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TB_TextsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TB_UserConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TB_UserChatroomConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
